### ISSUE TITLE
Relative image paths to the qgz file

### ISSUE THREAD

**Issue by bzeiss** [KIOS-Research/ImportPhotos#35]
I want to share my qgis folder with qgz, layers and pictures with a collegue, but his paths are all different from the imported photos. Is it somehow possible to have this plugin use relative paths?

**Comment by Mariosmsk** [comment]
Hi @bzeiss ,
`ImportPhotos v1.9` has been released. Check QGIS repository.
Thanks.

From descr.: When the user saves a project and wants to reopen it, the folder with the pictures should stay at the original file location or moved at the same location of the project (e.g. *.qgz) in order to be able to view the pictures.
